{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2025-2953",
        "assignerOrgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
        "state": "PUBLISHED",
        "assignerShortName": "VulDB",
        "dateReserved": "2025-03-29T19:35:04.653Z",
        "datePublished": "2025-03-30T15:31:04.853Z",
        "dateUpdated": "2025-03-31T13:06:13.447Z"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
                "shortName": "VulDB",
                "dateUpdated": "2025-03-30T15:31:04.853Z"
            },
            "title": "PyTorch torch.mkldnn_max_pool2d denial of service",
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "cweId": "CWE-404",
                            "lang": "en",
                            "description": "Denial of Service"
                        }
                    ]
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "PyTorch",
                    "versions": [
                        {
                            "version": "2.6.0+cu124",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A vulnerability, which was classified as problematic, has been found in PyTorch 2.6.0+cu124. Affected by this issue is the function torch.mkldnn_max_pool2d. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used."
                },
                {
                    "lang": "de",
                    "value": "Eine problematische Schwachstelle wurde in PyTorch 2.6.0+cu124 entdeckt. Es geht hierbei um die Funktion torch.mkldnn_max_pool2d. Dank Manipulation mit unbekannten Daten kann eine denial of service-Schwachstelle ausgenutzt werden. Der Angriff muss lokal passieren. Der Exploit steht zur öffentlichen Verfügung."
                }
            ],
            "metrics": [
                {
                    "cvssV4_0": {
                        "version": "4.0",
                        "baseScore": 4.8,
                        "vectorString": "CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N",
                        "baseSeverity": "MEDIUM"
                    }
                },
                {
                    "cvssV3_1": {
                        "version": "3.1",
                        "baseScore": 3.3,
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                        "baseSeverity": "LOW"
                    }
                },
                {
                    "cvssV3_0": {
                        "version": "3.0",
                        "baseScore": 3.3,
                        "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                        "baseSeverity": "LOW"
                    }
                },
                {
                    "cvssV2_0": {
                        "version": "2.0",
                        "baseScore": 1.7,
                        "vectorString": "AV:L/AC:L/Au:S/C:N/I:N/A:P"
                    }
                }
            ],
            "timeline": [
                {
                    "time": "2025-03-29T00:00:00.000Z",
                    "lang": "en",
                    "value": "Advisory disclosed"
                },
                {
                    "time": "2025-03-29T01:00:00.000Z",
                    "lang": "en",
                    "value": "VulDB entry created"
                },
                {
                    "time": "2025-03-29T20:40:07.000Z",
                    "lang": "en",
                    "value": "VulDB entry last update"
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "value": "Default436352 (VulDB User)",
                    "type": "reporter"
                }
            ],
            "references": [
                {
                    "url": "https://vuldb.com/?id.302006",
                    "name": "VDB-302006 | PyTorch torch.mkldnn_max_pool2d denial of service",
                    "tags": [
                        "vdb-entry",
                        "technical-description"
                    ]
                },
                {
                    "url": "https://vuldb.com/?ctiid.302006",
                    "name": "VDB-302006 | CTI Indicators (IOB, IOC, IOA)",
                    "tags": [
                        "signature",
                        "permissions-required"
                    ]
                },
                {
                    "url": "https://vuldb.com/?submit.521279",
                    "name": "Submit #521279 | pytorch PyTorch version: 2.6.0+cu124 Floating point exception",
                    "tags": [
                        "third-party-advisory"
                    ]
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/149274",
                    "tags": [
                        "issue-tracking"
                    ]
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/149274#issue-2923122269",
                    "tags": [
                        "exploit",
                        "issue-tracking"
                    ]
                }
            ]
        },
        "adp": [
            {
                "references": [
                    {
                        "url": "https://github.com/pytorch/pytorch/issues/149274",
                        "tags": [
                            "exploit"
                        ]
                    }
                ],
                "metrics": [
                    {
                        "other": {
                            "type": "ssvc",
                            "content": {
                                "timestamp": "2025-03-31T13:06:10.348201Z",
                                "id": "CVE-2025-2953",
                                "options": [
                                    {
                                        "Exploitation": "poc"
                                    },
                                    {
                                        "Automatable": "no"
                                    },
                                    {
                                        "Technical Impact": "partial"
                                    }
                                ],
                                "role": "CISA Coordinator",
                                "version": "2.0.3"
                            }
                        }
                    }
                ],
                "title": "CISA ADP Vulnrichment",
                "providerMetadata": {
                    "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                    "shortName": "CISA-ADP",
                    "dateUpdated": "2025-03-31T13:06:13.447Z"
                }
            }
        ]
    }
}