{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2023-28858",
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "dateUpdated": "2025-02-20T15:35:34.833Z",
        "dateReserved": "2023-03-26T00:00:00.000Z",
        "datePublished": "2023-03-26T00:00:00.000Z"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre",
                "dateUpdated": "2023-03-30T21:53:08.718Z"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "redis-py before 4.5.3 leaves a connection open after canceling an async Redis command at an inopportune time, and can send response data to the client of an unrelated request in an off-by-one manner. NOTE: this CVE Record was initially created in response to reports about ChatGPT, and 4.3.6, 4.4.3, and 4.5.3 were released (changing the behavior for pipeline operations); however, please see CVE-2023-28859 about addressing data leakage across AsyncIO connections in general."
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "n/a",
                    "versions": [
                        {
                            "version": "n/a",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://github.com/redis/redis-py/pull/2641"
                },
                {
                    "url": "https://github.com/redis/redis-py/issues/2624"
                },
                {
                    "url": "https://github.com/redis/redis-py/compare/v4.5.2...v4.5.3"
                },
                {
                    "url": "https://github.com/redis/redis-py/compare/v4.4.2...v4.4.3"
                },
                {
                    "url": "https://github.com/redis/redis-py/compare/v4.3.5...v4.3.6"
                },
                {
                    "url": "https://openai.com/blog/march-20-chatgpt-outage"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "text",
                            "lang": "en",
                            "description": "n/a"
                        }
                    ]
                }
            ]
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "af854a3a-2127-422b-91ae-364da2661108",
                    "shortName": "CVE",
                    "dateUpdated": "2024-08-02T13:51:38.740Z"
                },
                "title": "CVE Program Container",
                "references": [
                    {
                        "url": "https://github.com/redis/redis-py/pull/2641",
                        "tags": [
                            "x_transferred"
                        ]
                    },
                    {
                        "url": "https://github.com/redis/redis-py/issues/2624",
                        "tags": [
                            "x_transferred"
                        ]
                    },
                    {
                        "url": "https://github.com/redis/redis-py/compare/v4.5.2...v4.5.3",
                        "tags": [
                            "x_transferred"
                        ]
                    },
                    {
                        "url": "https://github.com/redis/redis-py/compare/v4.4.2...v4.4.3",
                        "tags": [
                            "x_transferred"
                        ]
                    },
                    {
                        "url": "https://github.com/redis/redis-py/compare/v4.3.5...v4.3.6",
                        "tags": [
                            "x_transferred"
                        ]
                    },
                    {
                        "url": "https://openai.com/blog/march-20-chatgpt-outage",
                        "tags": [
                            "x_transferred"
                        ]
                    }
                ]
            },
            {
                "metrics": [
                    {
                        "other": {
                            "type": "ssvc",
                            "content": {
                                "timestamp": "2025-02-20T15:35:20.640859Z",
                                "id": "CVE-2023-28858",
                                "options": [
                                    {
                                        "Exploitation": "none"
                                    },
                                    {
                                        "Automatable": "no"
                                    },
                                    {
                                        "Technical Impact": "partial"
                                    }
                                ],
                                "role": "CISA Coordinator",
                                "version": "2.0.3"
                            }
                        }
                    }
                ],
                "title": "CISA ADP Vulnrichment",
                "providerMetadata": {
                    "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
                    "shortName": "CISA-ADP",
                    "dateUpdated": "2025-02-20T15:35:34.833Z"
                }
            }
        ]
    }
}