{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2025-2720",
        "assignerOrgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
        "state": "REJECTED",
        "assignerShortName": "VulDB",
        "dateReserved": "2025-03-24T12:46:16.447Z",
        "datePublished": "2025-03-24T23:31:06.804Z",
        "dateUpdated": "2025-03-27T06:03:42.304Z",
        "dateRejected": "2025-03-27T06:03:42.304Z"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
                "shortName": "VulDB",
                "dateUpdated": "2025-03-27T06:03:42.304Z"
            },
            "rejectedReasons": [
                {
                    "lang": "en",
                    "value": "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: According to the code maintainer the call of the POC is invalid because the buffer pointed to by \"data\" must have \"len\" valid bytes. The docs were updated to make that clear."
                }
            ]
        }
    }
}